[package]
name = "rustclusterer"
version = "0.1.0"
authors = ["Johannes Opper <johannes.opper@gmail.com>"]

[dependencies]
rustc-serialize = "0.3"
libc            = "*"
serde = "*"

[lib]
name = "rustclusterer"
crate-type = ["dylib"]
